### ISSUE TITLE
Build error

### ISSUE THREAD

**Issue by DusperD** [CrestronCommunity/WebApp#1]
Hi,

I cloned this repository using Visual Studio 2022 and encountered the following error during the build process:

Projects that use central package version management should not define the version on the PackageReference items but on the PackageVersion items: Microsoft.AspNetCore.OpenApi; Swashbuckle.AspNetCore.

**Comment by DusperD** [comment]
changing Directory.Packages.props to

![Screenshot 2024-11-27 135404](https://github.com/user-attachments/assets/8156755d-3667-4ab7-8b3d-f8ab3853d36a)

changing MyApplication.csproj to

![Screenshot 2024-11-27 135544](https://github.com/user-attachments/assets/6245a465-37db-463d-92f9-6c89c0fc0083)

fixed it

**Comment by bitm0de** [comment]
Yeah it was probably missed as that was the latest project added. Thanks :)
